"""
Region definitions for OSM data download mapping.

Country → download URL resolution is driven by links.toml shipped with the package.
The library prefers the minified (address-only) PBF from static.osmosis.page
when available, falling back to the full Geofabrik extract.

Currently Germany-centric. See links.toml for available regions.
"""

from __future__ import annotations

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]
from dataclasses import dataclass
from importlib.resources import files


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RegionFile:
    """
    Represents a single downloadable OSM region file.

    Attributes:
        url:          Direct download URL (Geofabrik or static.osmosis.page)
        checksum_url: URL of the accompanying MD5 checksum file (may be empty)
        is_minified:  True if this is the address-only filtered version
    """

    url: str
    checksum_url: str
    is_minified: bool = False

    @property
    def cache_filename(self) -> str:
        """
        Derive a flat local cache filename from the URL.

        e.g. "https://static.osmosis.page/osm/DE-addresses-latest.osm.pbf"
             → "DE-addresses-latest.osm.pbf"
        """
        return self.url.rstrip("/").split("/")[-1]


@dataclass(frozen=True)
class CountryRegion:
    """
    Maps an ISO 3166-1 alpha-2 country code to its available OSM data files.

    Attributes:
        iso_code:       ISO 3166-1 alpha-2 code, e.g. "DE"
        name:           Human-readable country name, e.g. "Germany"
        full_file:      Full Geofabrik PBF (always available)
        minified_file:  Address-only filtered PBF from static.osmosis.page
                        (None if not yet generated by CI/CD)
    """

    iso_code: str
    name: str
    full_file: RegionFile
    minified_file: RegionFile | None = None

    @property
    def preferred_file(self) -> RegionFile:
        """
        Return the best available file to download.
        Prefers the minified version when available.
        """
        if self.minified_file is not None and self.minified_file.url:
            return self.minified_file
        return self.full_file

    @property
    def has_minified(self) -> bool:
        """True if a minified file has been generated and is available."""
        return self.minified_file is not None and bool(self.minified_file.url)


# ---------------------------------------------------------------------------
# Load country map from links.toml
# ---------------------------------------------------------------------------


def _load_country_region_map() -> dict[str, CountryRegion]:
    """
    Parse links.toml (from package data) and build the COUNTRY_REGION_MAP.

    Returns:
        Dict mapping ISO code → CountryRegion
    """
    # Read links.toml from package data (address_standardizer/data/links.toml)
    links_file = files("address_standardizer").joinpath("data", "links.toml")
    toml_content = links_file.read_bytes()
    data = tomllib.loads(toml_content.decode("utf-8"))

    countries = data.get("countries", {})
    result: dict[str, CountryRegion] = {}

    for iso_code, entry in countries.items():
        full_file = RegionFile(
            url=entry["source_url"],
            checksum_url=entry.get("source_checksum", ""),
            is_minified=False,
        )

        minified_url = entry.get("pbf_url", "")
        minified_file: RegionFile | None = None
        if minified_url:
            minified_file = RegionFile(
                url=minified_url,
                checksum_url=entry.get("checksum_url", ""),
                is_minified=True,
            )

        result[iso_code] = CountryRegion(
            iso_code=iso_code,
            name=entry["name"],
            full_file=full_file,
            minified_file=minified_file,
        )

    return result


# Loaded once at import time (from package data)
COUNTRY_REGION_MAP: dict[str, CountryRegion] = _load_country_region_map()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_country_region(iso_code: str) -> CountryRegion:
    """
    Look up a CountryRegion by ISO 3166-1 alpha-2 code.

    Args:
        iso_code: Two-letter country code, case-insensitive (e.g. "DE", "de")

    Returns:
        CountryRegion with full and (if available) minified download files

    Raises:
        ValueError: If the country code is not yet supported
    """
    key = iso_code.upper()
    if key not in COUNTRY_REGION_MAP:
        supported = ", ".join(sorted(COUNTRY_REGION_MAP.keys()))
        raise ValueError(
            f"Country code '{iso_code}' is not currently supported. "
            f"Supported countries: {supported}"
        )
    return COUNTRY_REGION_MAP[key]
